/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSimuladosRouteImport } from './routes/_app/simulados'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppRedacoesIndexRouteImport } from './routes/_app/redacoes/index'
import { Route as AppSimuladoIdRouteImport } from './routes/_app/simulado/$id'
import { Route as AppRedacoesNewRouteImport } from './routes/_app/redacoes/new'
import { Route as AppRedacoesIdIndexRouteImport } from './routes/_app/redacoes/$id/index'
import { Route as AppRedacoesIdEditRouteImport } from './routes/_app/redacoes/$id/edit'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSimuladosRoute = AppSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRedacoesIndexRoute = AppRedacoesIndexRouteImport.update({
  id: '/redacoes/',
  path: '/redacoes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSimuladoIdRoute = AppSimuladoIdRouteImport.update({
  id: '/simulado/$id',
  path: '/simulado/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRedacoesNewRoute = AppRedacoesNewRouteImport.update({
  id: '/redacoes/new',
  path: '/redacoes/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRedacoesIdIndexRoute = AppRedacoesIdIndexRouteImport.update({
  id: '/redacoes/$id/',
  path: '/redacoes/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRedacoesIdEditRoute = AppRedacoesIdEditRouteImport.update({
  id: '/redacoes/$id/edit',
  path: '/redacoes/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/simulados': typeof AppSimuladosRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/redacoes/new': typeof AppRedacoesNewRoute
  '/simulado/$id': typeof AppSimuladoIdRoute
  '/redacoes': typeof AppRedacoesIndexRoute
  '/redacoes/$id/edit': typeof AppRedacoesIdEditRoute
  '/redacoes/$id': typeof AppRedacoesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/simulados': typeof AppSimuladosRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/redacoes/new': typeof AppRedacoesNewRoute
  '/simulado/$id': typeof AppSimuladoIdRoute
  '/redacoes': typeof AppRedacoesIndexRoute
  '/redacoes/$id/edit': typeof AppRedacoesIdEditRoute
  '/redacoes/$id': typeof AppRedacoesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/simulados': typeof AppSimuladosRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/redacoes/new': typeof AppRedacoesNewRoute
  '/_app/simulado/$id': typeof AppSimuladoIdRoute
  '/_app/redacoes/': typeof AppRedacoesIndexRoute
  '/_app/redacoes/$id/edit': typeof AppRedacoesIdEditRoute
  '/_app/redacoes/$id/': typeof AppRedacoesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/configuracoes'
    | '/dashboard'
    | '/simulados'
    | '/login'
    | '/register'
    | '/redacoes/new'
    | '/simulado/$id'
    | '/redacoes'
    | '/redacoes/$id/edit'
    | '/redacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacidade'
    | '/termos'
    | '/configuracoes'
    | '/dashboard'
    | '/simulados'
    | '/login'
    | '/register'
    | '/redacoes/new'
    | '/simulado/$id'
    | '/redacoes'
    | '/redacoes/$id/edit'
    | '/redacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/privacidade'
    | '/termos'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/simulados'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/redacoes/new'
    | '/_app/simulado/$id'
    | '/_app/redacoes/'
    | '/_app/redacoes/$id/edit'
    | '/_app/redacoes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/simulados': {
      id: '/_app/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AppSimuladosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/redacoes/': {
      id: '/_app/redacoes/'
      path: '/redacoes'
      fullPath: '/redacoes'
      preLoaderRoute: typeof AppRedacoesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/simulado/$id': {
      id: '/_app/simulado/$id'
      path: '/simulado/$id'
      fullPath: '/simulado/$id'
      preLoaderRoute: typeof AppSimuladoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/redacoes/new': {
      id: '/_app/redacoes/new'
      path: '/redacoes/new'
      fullPath: '/redacoes/new'
      preLoaderRoute: typeof AppRedacoesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/redacoes/$id/': {
      id: '/_app/redacoes/$id/'
      path: '/redacoes/$id'
      fullPath: '/redacoes/$id'
      preLoaderRoute: typeof AppRedacoesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/redacoes/$id/edit': {
      id: '/_app/redacoes/$id/edit'
      path: '/redacoes/$id/edit'
      fullPath: '/redacoes/$id/edit'
      preLoaderRoute: typeof AppRedacoesIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSimuladosRoute: typeof AppSimuladosRoute
  AppRedacoesNewRoute: typeof AppRedacoesNewRoute
  AppSimuladoIdRoute: typeof AppSimuladoIdRoute
  AppRedacoesIndexRoute: typeof AppRedacoesIndexRoute
  AppRedacoesIdEditRoute: typeof AppRedacoesIdEditRoute
  AppRedacoesIdIndexRoute: typeof AppRedacoesIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSimuladosRoute: AppSimuladosRoute,
  AppRedacoesNewRoute: AppRedacoesNewRoute,
  AppSimuladoIdRoute: AppSimuladoIdRoute,
  AppRedacoesIndexRoute: AppRedacoesIndexRoute,
  AppRedacoesIdEditRoute: AppRedacoesIdEditRoute,
  AppRedacoesIdIndexRoute: AppRedacoesIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
